DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    first VARCHAR(45),
    second VARCHAR(45),
    password VARCHAR(45),
    PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS docs;
CREATE TABLE docs (
    id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id int(10) UNSIGNED,
    name VARCHAR(45),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

